export const GET_PROVINCE_REQUEST = 'GET_PROVINCE_REQUEST';
export const GET_PROVINCE_SUCCESS = 'GET_PROVINCE_SUCCESS';
export const GET_PROVINCE_ERROR = 'GET_PROVINCE_ERROR';

export const GET_CITY_REQUEST = 'GET_CITY_REQUEST';
export const GET_CITY_SUCCESS = 'GET_CITY_SUCCESS';
export const GET_CITY_ERROR = 'GET_CITY_ERROR';

export const GET_COST_REQUEST = 'GET_COST_REQUEST';
export const GET_COST_SUCCESS = 'GET_COST_SUCCESS';
export const GET_COST_ERROR = 'GET_COST_ERROR';

export const POSTS_DATA_REQUEST = 'POSTS_DATA_REQUEST';
export const POSTS_DATA_SUCCESS = 'POSTS_DATA_SUCCESS';
export const POSTS_DATA_ERROR = 'POSTS_DATA_ERROR';
